version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SECRET_KEY
    volumes:
      - frontendstatics:/app/frontend

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8123:80
    volumes:
      - frontendstatics:/srv/frontend:ro

volumes:
  frontendstatics:
