version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  redis:
    image: redis

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - frontendstatics:/app/frontend

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        env: $TARGET_ENV
    depends_on:
      - app
    ports:
      - "127.0.0.1:8123:80"
    volumes:
      - frontendstatics:/srv/frontend:ro

volumes:
  frontendstatics:
